sfapp/src/Entity/Plan.php
<?php

namespace App\Entity;

use App\Repository\PlanRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: PlanRepository::class)]
class Plan
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\ManyToOne(inversedBy: 'plans')]
    private ?Salle $salle = null;

    #[ORM\OneToOne(inversedBy: 'plan', cascade: ['persist', 'remove'])]
    private ?SystemAcquisition $SA = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $date_association = null;

    #[ORM\Column(type: Types::DATE_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $date_desassociation = null;

    public function __construct()
    {
        $this->notes = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getSalle(): ?Salle
    {
        return $this->salle;
    }

    public function setSalle(?Salle $salle): static
    {
        $this->salle = $salle;

        return $this;
    }

    public function getSA(): ?SystemAcquisition
    {
        return $this->SA;
    }

    public function setSA(SystemAcquisition $SA): static
    {
        $this->SA = $SA;

        return $this;
    }

    public function getDateAssociation(): ?\DateTimeInterface
    {
        return $this->date_association;
    }

    public function setDateAssociation(\DateTimeInterface $date_association): static
    {
        $this->date_association = $date_association;

        return $this;
    }

    public function getDateDesassociation(): ?\DateTimeInterface
    {
        return $this->date_desassociation;
    }

    public function setDateDesassociation(?\DateTimeInterface $date_desassociation): static
    {
        $this->date_desassociation = $date_desassociation;

        return $this;
    }
}

sfapp/src/Form/PlanType.php
<?php

namespace App\Form;

use App\Entity\Plan;
use App\Entity\Salle;
use App\Entity\SystemAcquisition;
use App\Repository\SystemAcquisitionRepository;
use App\Repository\SalleRepository;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class PlanType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('salle', EntityType::class, [
                'class' => Salle::class,
                'label' => 'Salle : ',
                'choice_label' => 'nom',
                'query_builder' => function(SalleRepository $salleRepository) use ($options) {
                    return $salleRepository->findByBatiment($options['v_batiment']);
                }
            ])
            ->add('SA', EntityType::class, [
                'class' => SystemAcquisition::class,
                'label' => false,
                'choice_label' => 'nom',
                'query_builder' => function(SystemAcquisitionRepository $systemeAcquisitionRepository){
                    return $systemeAcquisitionRepository->getAllAvalailableSA();
                }
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Plan::class,
            'v_batiment' => '',
        ]);
    }
}

sfapp/src/Controller/PlanController.php
<?php

namespace App\Controller;

use App\Entity\Note;
use App\Entity\TypeNote;
use App\Form\AddNoteType;
use App\Repository\NoteRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Session\SessionInterface;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Http\Attribute\IsGranted;
use Symfony\Config\Doctrine\Dbal\ConnectionConfig\ReplicaConfig;
use Doctrine\ORM\EntityManager;
use Doctrine\ORM\EntityManagerInterface;
use App\Entity\Etat;
use App\Entity\Plan;
use App\Repository\PlanRepository;
use App\Repository\SystemAcquisitionRepository;
use App\Repository\SalleRepository;
use App\Form\PlanType;
use App\Form\ChangeEtatType;
use function PHPUnit\Framework\throwException;

class PlanController extends AbstractController
{
    // ROUTE PRINCIPALE
    // route pour afficher la liste des salles dans le plan
    #[Route('/plan', name: 'app_plan')]
    #[IsGranted("ROLE_TECHNICIEN", message: 'Vous devez être connecté pour avoir accès à cette page.')]
    public function plan(PlanRepository $planRepository, SystemAcquisitionRepository $systemAcquisitionRepository, SalleRepository $salleRepository, Request $request): Response
    {
        //état des capteurs pour le tri
        $etats = Etat::cases();

        // sauvegarde l'url de la page
        $url = $request->getUri();
        $session = $request->getSession();
        $session->set('previous_url', $url);

        return $this->render('plan/index.html.twig', [
            'etats' => $etats,
        ]);
    }

    // ROUTE PRINCIPALE
    // route pour ajouter une nouvelle association
    #[Route('/plan/nouveau/{idSalle}', name: 'app_plan_nouveau')]
    #[IsGranted("ROLE_CHARGEMISSION", message: 'Vous n\'avez pas les autorisations requises pour accéder à cette page.')]
    public function nouveau(int $idSalle, Request $request, EntityManagerInterface $manager, PlanRepository $planRepository, SalleRepository $salleRepository, SessionInterface $session): Response
    {
        $batimentNom = $session->get('batiment_selectioné_nom');
        $plan = new Plan();

        // idSalle = -1 quand on crée une association sans salle précise
        // sinon idSalle = l'id de la salle qu'on a choisi
        if($idSalle != -1)
        {
            // on récupère l'id de la salle et on l'associe au plan
            $salle = $salleRepository->findOneBy(['id' => $idSalle]);
            $plan->setSalle($salle);
        }
        else
        {
            $salle = $salleRepository->findOneBy(['id' => $idSalle]);
        }

        $form = $this->createForm(PlanType::class, $plan, [
            'v_batiment' => $batimentNom,
        ]);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) 
        {
            // push dans la base de donnée
            $plan->setDateAssociation(new \DateTime);

            $manager->persist($plan);
                
            $manager->flush();

            $this->addFLash('message', "Le SA a bien été associé à la salle");

            if($idSalle == -1)
            {
                //redirige vers le plan
                return $this->redirectToRoute('app_plan');
            }
            else
            {
                // redirige vers la page précédente
                $session = $request->getSession();
                $url = $session->get('previous_url');
                return $this->redirect($url);
            }
        }

        return $this->render('plan/new.html.twig', [
            'form' => $form,
            'salle' => $salle
        ]);
    }

    // route pour visualiser en détail et modifier un plan
    #[Route('/plan/modifier/{idSalle}', name: 'app_plan_modifier')]
    #[IsGranted("ROLE_TECHNICIEN", message: 'Vous devez être connecté pour avoir accès à cette page.')]
    public function modifier(int $idSalle, SalleRepository $salleRepository, PlanRepository $planRepository, NoteRepository $noteRepository,SystemAcquisitionRepository $systemAcquisitionRepository, Request $request, EntityManagerInterface $manager, SessionInterface $session): Response
    {
        $batimentNom = $session->get('batiment_selectioné_nom');
        $salle = $salleRepository->findOneBy(['id' => $idSalle]);

        // liste des sa de la salle
        $plans = $planRepository->findBySalle($idSalle, $batimentNom);

        // pour changer l'état des sa
        $etats = Etat::cases();

        //création et validation des formulaires pour chaque sa
        $forms = [];
        foreach($plans as $plan)
        {
            $sa = $systemAcquisitionRepository->findByName($plan["nom"]);

            // création du formulaire
            $form = $this->createForm(ChangeEtatType::class, $sa);
            $form->handleRequest($request);
            //on récupère le nom du sa qui a été modifié
            $nomSA = $form->get('isSubmit')->getData();

            if ($form->isSubmitted() && $form->isValid() && $sa->getNom() == $nomSA) 
            {
                // redirection vers la route de validation de modification
                return $this->redirectToRoute('app_plan_modification', [
                    'idSalle' => $idSalle,
                    'nomSA' => $nomSA,
                    'etat' => $sa->getEtat()->value,
                ]);
            }

            // on stock les forms dans un tableau pour les afficher
            $forms[$sa->getNom()] = $form->createView();
        }

        $Note = new Note();

        $form = $this->createForm(AddNoteType::class, $Note, []);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid())
        {
            $Note->setType(TypeNote::Information);
            $Note->setSalle($salle);
            $Note->setDate(new \DateTime);
            $manager->persist($Note);
            $manager->flush();

            // Recrée un formulaire vierge
            $note = new Note();
            $form = $this->createForm(AddNoteType::class, $note, []);

            $this->addFlash('message', 'Note ajoutée avec succès!');

            return $this->redirectToRoute('app_plan_modifier',[
                    'idSalle' => $idSalle,
            ]);

        }

        $listNote= $noteRepository->findBySalle($batimentNom, $idSalle);
        $typeNote = TypeNote::cases();

        // sauvegarde l'url de la page
        $url = $request->getUri();
        $session = $request->getSession();
        $session->set('previous_url', $url);

        return $this->render('plan/edit.html.twig', [
            'salle' => $salle,
            'plans' => $plans,
            'etats' => $etats,
            'forms' => $forms,
            'form' => $form,
            'listNote' => $listNote,
            'typeNote' => $typeNote,
        ]);
    }

    #[Route(path: '/plan/problemelu/{idProbleme}', name: 'app_plan_probleme')]
    public function probleme(int $idProbleme, EntityManagerInterface $manager, NoteRepository $noteRepository): Response
    {
        $note= $noteRepository->findOneById($idProbleme);

        $note->setType(TypeNote::ProblemeLu);
        $note->setDate(new \DateTime());
        $manager->persist($note);
        $manager->flush();

        return $this->redirectToRoute('app_plan_modifier', [
            'idSalle' => $note->getSalle()->getId(),
        ]);
    }

    /**
     * @author Côme, Axel
     * @brief change le type de la note pour "lu" suivant son type d'origine (normale ou batiment)
     * @param int $idProbleme l'id de la note
     * @param EntityManagerInterface $manager le manager pour persist et flush les données
     * @param NoteRepository $noteRepository le repository pour récupérer l'entité note
     * @return Response
     */
    #[Route(path: '/plan/problemelu/dashboard/{idProbleme}', name: 'app_plan_probleme_dashboard')]
    public function probleme_dashboard(int $idProbleme, EntityManagerInterface $manager, NoteRepository $noteRepository): Response
    {
        $note = $noteRepository->findOneById($idProbleme); // récupère la note

        switch($note->getType())
        {
            case TypeNote::Probleme:
                $note->setType(TypeNote::ProblemeLu);
                break;
            case TypeNote::ProblemeBatiment:
                $note->setType(TypeNote::ProblemeBatimentLu);
                break;
            default:
                $this->addFlash("message", "Erreur lors de la modification du problème");
                break;
        }


        $note->setDate(new \DateTime());
        $manager->persist($note);
        $manager->flush();

        $this->addFlash("message", "Problème lue");

        return $this->redirectToRoute('app_dashboard', []);
    }

     // route valider la modification d'un état
    #[Route('/plan/modifier/{idSalle}/{nomSA}/{etat}', name: 'app_plan_modification')]
    #[IsGranted("ROLE_TECHNICIEN", message: 'Vous devez être connecté pour avoir accès à cette page.')]
    public function modification(int $idSalle, string $nomSA, Etat $etat, SystemAcquisitionRepository $systemAcquisitionRepository, EntityManagerInterface $manager): Response
    {
        // on recup le sa à partir du nom
        $sa = $systemAcquisitionRepository->findByName($nomSA);
        // on lui attribue l'état
        $sa->setEtat($etat);

        $manager->persist($sa);
        $manager->flush();

        // on revient sur la page précédente
        return $this->redirectToRoute('app_plan_modifier', [
            'idSalle' => $idSalle,
        ]);
    }

    // route de l'historique des plans
    #[Route('/plan/historique/{nom}', name: 'app_plan_historique', defaults: ['nom' => 'none'])]
    #[IsGranted("ROLE_TECHNICIEN", message: 'Vous devez être connecté pour avoir accès à cette page.')]

sfapp/templates/plan/historique.html.twig
{% extends 'base.html.twig' %}

{% block title %}Historique{% endblock %}

{% block content %}
    <link rel="stylesheet" href="{{ asset('style/historique.css') }}">
{% endblock %}

{% block header %}
    <div class="header-titre">
        <p id="header-titre"><strong>HISTORIQUE</strong></p><div id="bar"></div><p id="header-titre-batiment">batiment : <strong>{{ batiment_nom }}</strong></p>
    </div>
{% endblock %}

{% block body %}
    <div id="page-body">

        <!-- Liste des plans -->
        <div id="plan-list" class="container">
            <!-- Barre de recherche -->
            <div id="recherche">
                <input type="text" id="search-bar" placeholder="Rechercher une salle ou un sa...">
                <button type="button" id="search-btn" class="button-type1 button-confirm">Rechercher</button>
            </div>
            <div id="plan-list-limit">
            {% for plan in plans %}
                <div class="plan">
                    <p>SALLE {{ plan.salle.nom }}</p>
                    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512"><path d="M438.6 150.6c12.5-12.5 12.5-32.8 0-45.3l-96-96c-12.5-12.5-32.8-12.5-45.3 0s-12.5 32.8 0 45.3L338.7 96 32 96C14.3 96 0 110.3 0 128s14.3 32 32 32l306.7 0-41.4 41.4c-12.5 12.5-12.5 32.8 0 45.3s32.8 12.5 45.3 0l96-96zm-333.3 352c12.5 12.5 32.8 12.5 45.3 0s12.5-32.8 0-45.3L109.3 416 416 416c17.7 0 32-14.3 32-32s-14.3-32-32-32l-306.7 0 41.4-41.4c12.5-12.5 12.5-32.8 0-45.3s-32.8-12.5-45.3 0l-96 96c-12.5 12.5-12.5 32.8 0 45.3l96 96z"/></svg>
                    <p>SA {{ plan.SA.nom }}</p>
                    <p class="date">attribué le {{ plan.dateAssociation|date('d/m/Y') }}</p>
                    <p> | </p>
                    {% if plan.dateDesassociation is null %}
                        <p class="date">- - -</p>
                    {% else %}
                        <p class="date">enlevé le {{ plan.dateDesassociation|date('d/m/Y')}}</p>
                    {% endif %}
                </div>
            {% endfor %}
            </div>
        </div>

        <a href="{{ path('app_plan') }}" class="button-type1 button-cancel" id="delete-btn">
            FERMER
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 384 512">
                <path d="M342.6 150.6c12.5-12.5 12.5-32.8 0-45.3s-32.8-12.5-45.3 0L192 210.7 86.6
                    105.4c-12.5-12.5-32.8-12.5-45.3 0s-12.5 32.8 0 45.3L146.7 256 41.4 361.4c-12.5 12.5-12.5 32.8 0
                    45.3s32.8 12.5 45.3 0L192 301.3 297.4 406.6c12.5 12.5 32.8 12.5 45.3 0s12.5-32.8 0-45.3L237.3 256
                    342.6 150.6z"/>
            </svg>
        </a>
        
    </div>

    <script src="{{ asset('js/rechercheHistorique.js') }}"></script>

{% endblock %}

sfapp/templates/plan/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Plan{% endblock %}

{% block content %}
    <link rel="stylesheet" href="{{ asset('style/plan.css') }}">
{% endblock %}

{% block header %}
    <div class="header-titre">
        <p id="header-titre"><strong>PLAN</strong></p><div id="bar"></div><p id="header-titre-batiment">batiment : <strong>{{ batiment_nom }}</strong></p>
    </div>
{% endblock %}

{% block body %}
    <!-- popup de confirmation -->
    <div id="message-confirmation">
        <p>Etes-vous sur de vouloir désassocier ce SA ?</p>
        <button id="confirm-cancel-button" class="button-type2 button-cancel"> ANNULER</button>
        <button id="confirm-delete-button" class="button-type2 button-confirm" data-delete-salle="true"> SUPPRIMER</button>
    </div>

    <div id="page-body">
        <div id="filter">
            <!-- Barre de recherche -->
            <input
                type="text"
                id="search-bar"
                placeholder="Rechercher une salle ou un sa..."
                >

            <!-- Liste étage -->
            <select id="list-etat" class="list-options">
                <option value="tout">Tout</option>
                {% for etat in  etats %}
                    <option value="{{ etat.value }}">{{ etat.value }}</option>
                {% endfor %}
            </select>

            <div id="separator"></div>

            {% if is_granted("ROLE_CHARGEMISSION") %}
            <a href="{{ path('app_plan_nouveau', {'idSalle':-1}) }}" class="plan-btn">Créer une association</a>
            {% endif %}

            <a href="{{ path('app_plan_historique') }}" class="plan-btn">Historique</a>
        </div>

        <!-- Liste des plans -->
        <div id="plan-list"></div>
    </div>
{% endblock %}

{% block script %}
    {# Script pour passer les rôles de l'utilisateur au JS #}
    <script>
        const rolesUtilisateur =
        {% if is_granted("IS_AUTHENTICATED_FULLY") %}
            {{ app.user.roles | json_encode | raw }}
        {% else %}
            []
        {% endif %}
        ;
    </script>

    <script src="{{ asset('js/affichagePlan.js') }}"></script>
{% endblock %}

sfapp/templates/plan/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Ajouter une association{% endblock %}

{% block content %}
    <link rel="stylesheet" href="{{ asset('style/ajoutPlan.css') }}">
{% endblock %}

{% block header %}
    <div class="header-titre">
        <p id="header-titre"><strong>AJOUTER UNE ASSOCIATION</strong></p><div id="bar"></div><p id="header-titre-batiment">batiment : <strong>{{ batiment_nom }}</strong></p>
    </div>
{% endblock %}

{% block body %}
    <div id="page-body">
        <div id="body-left">
            <div id="form" class="container">
            {{ form_start(form, {'attr':{'id':'ajoutPlanForm'}})}}
                <div id="form-left">
                    {{ form_row(form.salle)}}
                    <div id="form-left-historique">
                        <!-- svg -->
                        {% if salle==null %}
                        <a href="{{ path('app_plan_historique') }}">HISTORIQUE DES ATTRIBUTIONS</a>
                        {% else %}
                        <a href="{{ path('app_plan_historique', {'nom':salle.nom}) }}">HISTORIQUE DES ATTRIBUTIONS</a>
                        {% endif %}
                    </div>
                </div>

                <div id="form-separator"></div>

                <div id="form-right">
                    <div id="form-right-sa">
                        <p><strong>SA</strong> associé : </p>
                        {{ form_row(form.SA) }}
                    </div>
                </div>
            {{ form_end(form) }}
            </div>

            <div id="notes">
            </div>
        </div>

        <div id="body-right">
            <div id="infos">
                <div id="infos-historique-notes">
                </div>

                <div id="infos-separator"></div>

                <div id="infos-guideline">
                    <div id="infos-guideline-top">
                        <!-- svg livre -->
                        <svg width="64px" height="64px" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg"><g id="SVGRepo_bgCarrier" stroke-width="0"></g><g id="SVGRepo_tracerCarrier" stroke-linecap="round" stroke-linejoin="round"></g><g id="SVGRepo_iconCarrier"> <path d="M12 10.4V20M12 10.4C12 8.15979 12 7.03969 11.564 6.18404C11.1805 5.43139 10.5686 4.81947 9.81596 4.43597C8.96031 4 7.84021 4 5.6 4H4.6C4.03995 4 3.75992 4 3.54601 4.10899C3.35785 4.20487 3.20487 4.35785 3.10899 4.54601C3 4.75992 3 5.03995 3 5.6V16.4C3 16.9601 3 17.2401 3.10899 17.454C3.20487 17.6422 3.35785 17.7951 3.54601 17.891C3.75992 18 4.03995 18 4.6 18H7.54668C8.08687 18 8.35696 18 8.61814 18.0466C8.84995 18.0879 9.0761 18.1563 9.29191 18.2506C9.53504 18.3567 9.75977 18.5065 10.2092 18.8062L12 20M12 10.4C12 8.15979 12 7.03969 12.436 6.18404C12.8195 5.43139 13.4314 4.81947 14.184 4.43597C15.0397 4 16.1598 4 18.4 4H19.4C19.9601 4 20.2401 4 20.454 4.10899C20.6422 4.20487 20.7951 4.35785 20.891 4.54601C21 4.75992 21 5.03995 21 5.6V16.4C21 16.9601 21 17.2401 20.891 17.454C20.7951 17.6422 20.6422 17.7951 20.454 17.891C20.2401 18 19.9601 18 19.4 18H16.4533C15.9131 18 15.643 18 15.3819 18.0466C15.15 18.0879 14.9239 18.1563 14.7081 18.2506C14.465 18.3567 14.2402 18.5065 13.7908 18.8062L12 20" stroke="#2BA801" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"></path> </g></svg>
                        <p>Guideline</p>
                        <a href="{{ asset('guideline.pdf') }}" target="_blank" class="button-type2 button-confirm">Cliquer pour voir</a>
                    </div>
                    <div id="infos-guideline-separator"></div>
                    <p id="infos-guideline-texte">Guide d'installation des sa (PDF)</p>
                </div>
            </div>
            
            <div id="edit-button-container">
                <a href="{{ app.request.headers.get('referer') ?: path('default_route') }}" class="bouton-crud button-type1 button-cancel" id="delete-btn">
                    ANNULER
                    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 384 512">
                        <path d="M342.6 150.6c12.5-12.5 12.5-32.8 0-45.3s-32.8-12.5-45.3 0L192 210.7 86.6
                                105.4c-12.5-12.5-32.8-12.5-45.3 0s-12.5 32.8 0 45.3L146.7 256 41.4 361.4c-12.5 12.5-12.5 32.8 0
                                45.3s32.8 12.5 45.3 0L192 301.3 297.4 406.6c12.5 12.5 32.8 12.5 45.3 0s12.5-32.8 0-45.3L237.3 256
                                342.6 150.6z"/>
                    </svg>
                </a>
                <button type="submit" form="ajoutPlanForm" class="bouton-crud button-type1 button-confirm" id="edit-btn">
                    VALIDER
                    <!-- check icon -->
                    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512">
                        <path d="M438.6 105.4c12.5 12.5 12.5 32.8 0 45.3l-256 256c-12.5 12.5-32.8 12.5-45.3
                                0l-128-128c-12.5-12.5-12.5-32.8 0-45.3s32.8-12.5 45.3 0L160 338.7 393.4 105.4c12.5-12.5 32.8-12.5
                                45.3 0z"/>
                    </svg>
                </button>
            </div>
        </div>
    </div>
{% endblock %}